version: "3.8"

services:
  drc-docker-platform.local:
    image: harbor.contezza.nl/utrecht/drc/platform:latest
    environment:
      TZ: Europe/Amsterdam
      JAVA_TOOL_OPTIONS: "
        -Dencryption.keystore.type=JCEKS
        -Dencryption.cipherAlgorithm=DESede/CBC/PKCS5Padding
        -Dencryption.keyAlgorithm=DESede
        -Dencryption.keystore.location=/usr/local/tomcat/shared/classes/alfresco/extension/keystore/keystore
        -Dmetadata-keystore.password=mp6yc0UD9e
        -Dmetadata-keystore.aliases=metadata
        -Dmetadata-keystore.metadata.password=oKIWzVdEdA
        -Dmetadata-keystore.metadata.algorithm=DESede
        -Dmail.poller.enabled=true
        "
      JAVA_OPTS: "
       -Ddb.url=jdbc:postgresql://db:5432/alfresco
       -Dalfresco.host=drc-docker-platform.local
       -Dalfresco.port=8080
       -Xms2g -Xmx2g
       -Ddrc.siteShortname=swsdp
       -Ddrc.nrc.basePath=http://open-notificaties.local:8000/api/v1
       -Ddrc.nrc.clientId=openzaak
       -Ddrc.nrc.secret=openzaak
       -Ddrc.ztc.basePath=http://open-zaak.local:8000/catalogi/api/v1
       -Ddrc.ztc.clientId=openzaak
       -Ddrc.ztc.secret=openzaak
       -Ddrc.zrc.basePath=http://open-zaak.local:8000/zaken/api/v1
       -Ddrc.zrc.clientId=openzaak
       -Ddrc.zrc.secret=openzaak
       -Ddrc.brc.basePath=http://open-zaak.local:8000/besluiten/api/v1
       -Ddrc.brc.clientId=openzaak
       -Ddrc.brc.secret=openzaak
       -Ddrc.ac.enabled=true
       -Ddrc.ac.basePath=http://open-zaak.local:8000/autorisaties/api/v1
       -Ddrc.ac.clientId=openzaak
       -Ddrc.ac.secret=openzaak
       -Djwt.authentication.config=alfresco/extension/jwt/jwt.json
      "
    ports:
      - "8080:8080"
    volumes:
      - vol_drc-docker-platform_alf_data:/usr/local/tomcat/alf_data
    depends_on:
      - db
      - drc-docker-platform-ass
      - drc-docker-platform-activemq
      - transform-router
      - transform-core-aio
      - shared-file-store
    networks:
     dev_network:
      aliases:
       - drc-docker-platform.local

  drc-docker-share:
    image: harbor.contezza.nl/utrecht/drc/share:latest
    environment:
     REPO_HOST: "drc-docker-platform.local"
     REPO_PORT: "8080"
    ports:
     - "8081:8080"

  drc-docker-platform-ass:
    image: harbor.contezza.nl/base/alfresco-search-services:2.0.6
    environment:
      TZ: Europe/Amsterdam
      SOLR_ALFRESCO_HOST: drc-docker-platform.local
      SOLR_ALFRESCO_PORT: "8080"
      SOLR_SOLR_HOST: drc-docker-platform-ass
      SOLR_SOLR_PORT: "8983"
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
      JAVA_TOOL_OPTIONS: "-Dalfresco.secureComms=secret -Dalfresco.secureComms.secret=secret"
    volumes:
      - vol_drc-docker-platform_solr_data:/opt/alfresco-search-services/data
    networks:
      - dev_network

  drc-docker-platform-activemq:
    image: harbor.contezza.nl/docker.io/alfresco/alfresco-activemq:5.16.1
    networks:
      - dev_network

  transform-router:
    image: harbor.contezza.nl/quay.io/alfresco/alfresco-transform-router:1.2.0
    environment:
      JAVA_OPTS: " -Xms256m -Xmx512m"
      ACTIVEMQ_URL: nio://drc-docker-platform-activemq:61616
      CORE_AIO_URL: http://transform-core-aio:8090
      FILE_STORE_URL: http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file
    networks:
      - dev_network

  transform-core-aio:
    image: harbor.contezza.nl/quay.io/alfresco/alfresco-transform-core-aio:2.6.0
    environment:
      JAVA_OPTS: "
       -Xms700m -Xmx700m
       "
      ACTIVEMQ_URL: nio://drc-docker-platform-activemq:61616
      FILE_STORE_URL: http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file
    networks:
      - dev_network

  shared-file-store:
    image: harbor.contezza.nl/quay.io/alfresco/alfresco-shared-file-store:1.5.3
    environment:
      JAVA_OPTS: " -Xms256m -Xmx512m"
      scheduler.content.age.millis: "86400000"
      scheduler.cleanup.interval: "86400000"
    # ports:
    #  - 8099:8099
    volumes:
      - vol_drc-docker-platform_shared_file_store:/tmp/Alfresco/sfs
    networks:
      - dev_network

networks:
 dev_network:
  external: true

volumes:
  vol_drc-docker-platform_alf_data:
  vol_drc-docker-platform_solr_data:
  vol_drc-docker-platform_shared_file_store:
