version: "3.8"

services:
  drc-docker-platform.local:
    image: hub.contezza.nl/projecten/utrecht/drc/platform:latest
    environment:
      TZ: Europe/Amsterdam
      JAVA_OPTS: "
       -Ddb.url=jdbc:postgresql://db:5432/alfresco
       -Dalfresco.host=drc-docker-platform.local
       -Dalfresco.port=8080
       -Xms2g -Xmx2g
       -Ddrc.siteShortname=swsdp
       -Ddrc.nrc.basePath=http://open-notificaties.local:8000/api/v1
       -Ddrc.nrc.clientId=openzaak
       -Ddrc.nrc.secret=openzaak
       -Ddrc.ztc.basePath=http://open-zaak.local:8000/catalogi/api/v1
       -Ddrc.ztc.clientId=openzaak
       -Ddrc.ztc.secret=openzaak
       -Ddrc.zrc.basePath=http://open-zaak.local:8000/zaken/api/v1
       -Ddrc.zrc.clientId=openzaak
       -Ddrc.zrc.secret=openzaak
       -Ddrc.brc.basePath=http://open-zaak.local:8000/besluiten/api/v1
       -Ddrc.brc.clientId=openzaak
       -Ddrc.brc.secret=openzaak
       -Ddrc.ac.enabled=true
       -Ddrc.ac.basePath=http://open-zaak.local:8000/autorisaties/api/v1
       -Ddrc.ac.clientId=openzaak
       -Ddrc.ac.secret=openzaak
       -Djwt.authentication.config=alfresco/extension/jwt/jwt.json
      "
    ports:
      - "8080:8080"
    volumes:
      - vol_drc-docker-platform_alf_data:/usr/local/tomcat/alf_data
    depends_on:
      - db
      - drc-docker-platform-ass
      - drc-docker-platform-activemq
      - transform-router
      - transform-core-aio
      - shared-file-store
    networks:
     dev_network:
      aliases:
       - drc-docker-platform.local

#  drc-docker-share:
#    image: hub.contezza.nl/projecten/utrecht/drc/share:latest
#    environment:
#      REPO_HOST: "drc-docker-platform.local"
#      REPO_PORT: "8080"
#    ports:
#      - "8081:8080"

  drc-docker-platform-ass:
    image: alfresco/alfresco-search-services:1.4.1.2
    environment:
      TZ: Europe/Amsterdam
      SOLR_ALFRESCO_HOST: drc-docker-platform.local
      SOLR_ALFRESCO_PORT: "8080"
      SOLR_SOLR_HOST: drc-docker-platform-ass
      SOLR_SOLR_PORT: "8983"
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
      ALFRESCO_SECURE_COMMS: none
    ports:
      - "8983:8983"
    volumes:
      - vol_drc-docker-platform_solr_data:/opt/alfresco-search-services/data

  drc-docker-platform-activemq:
    image: alfresco/alfresco-activemq:5.15.8
    ports:
      - 8161:8161 # Web Console
      - 5672:5672 # AMQP
      - 61616:61616 # OpenWire
      - 61613:61613 # STOMP

  transform-router:
    image: hub.contezza.nl/projecten/utrecht/alfresco-transform-router:1.2.0
    environment:
      JAVA_OPTS: " -Xms256m -Xmx512m"
      ACTIVEMQ_URL: nio://drc-docker-platform-activemq:61616
      CORE_AIO_URL: http://transform-core-aio:8090
      FILE_STORE_URL: http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file
    ports:
      - 8095:8095

  transform-core-aio:
    image: alfresco/alfresco-transform-core-aio:2.2.2
    environment:
      JAVA_OPTS: "
       -Xms700m -Xmx700m
       "
      ACTIVEMQ_URL: nio://drc-docker-platform-activemq:61616
      FILE_STORE_URL: http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file
    # ports:
    #   - 8090:8090

  shared-file-store:
    image: alfresco/alfresco-shared-file-store:0.5.3
    environment:
      JAVA_OPTS: " -Xms256m -Xmx512m"
      scheduler.content.age.millis: "86400000"
      scheduler.cleanup.interval: "86400000"
    # ports:
    #  - 8099:8099
    volumes:
      - vol_drc-docker-platform_shared_file_store:/tmp/Alfresco/sfs

networks:
 dev_network:
  external: true

volumes:
  vol_drc-docker-platform_alf_data:
  vol_drc-docker-platform_solr_data:
  vol_drc-docker-platform_shared_file_store:
